name: nichesphenv
channels:
  - conda-forge
  - defaults
dependencies:
  - graphviz=12.0.0=hba01fac_0
  - jupyterlab=4.3.3=pyhd8ed1ab_0
  - pygraphviz=1.14=py310h9a1d609_0
  - python=3.10.16=he725a3c_1_cpython
  - pip:
      - poetry==1.8.5
